# Generated by Django 3.2.13 on 2022-06-29 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220629_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='dateTime',
            new_name='post_date',
        ),
    ]
