# Generated by Django 3.2.13 on 2022-06-29 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_datetime_blogpost_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='post_date',
        ),
    ]
