# Generated by Django 3.2.13 on 2022-07-25 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Twitter',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='linkedin',
        ),
    ]
